### ISSUE TITLE
Reflector crashing when cert-manager is not installed

### ISSUE THREAD

**Issue by aeimer** [emberstack/kubernetes-reflector#89]
I just installed:

```yaml
- name: reflector
  namespace: reflector
  chart: emberstack/reflector
  version: 5.3.16
```

with

```yaml
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
```

the pod now always crahes with:

```shell
2020-09-18 08:35:40.883 +00:00 [INF] (ES.Kubernetes.Reflector.Host.Program) Starting host
2020-09-18 08:37:28.791 +00:00 [ERR] (ES.Kubernetes.Reflector.CertManager.CertManagerMonitor) V1CustomResourceDefinition watcher Faulted
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.WatcherDelegatingHandler.PeekableStreamReader.PeekLineAsync()
   at k8s.WatcherDelegatingHandler.LineSeparatedHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.ListCustomResourceDefinitionWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.CertManager.CertManagerMonitor.<>c.<<-ctor>b__10_2>d.MoveNext() in /src/ES.Kubernetes.Reflector.CertManager/CertManagerMonitor.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at ES.Kubernetes.Reflector.Core.Monitoring.ManagedWatcher`3.Start() in /src/ES.Kubernetes.Reflector.Core/Monitoring/ManagedWatcher.cs:line 100
2020-09-18 08:37:29.385 +00:00 [FTL] (ES.Kubernetes.Reflector.Host.Program) Host terminated unexpectedly
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.WatcherDelegatingHandler.PeekableStreamReader.PeekLineAsync()
   at k8s.WatcherDelegatingHandler.LineSeparatedHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.ListCustomResourceDefinitionWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.CertManager.CertManagerMonitor.<>c.<<-ctor>b__10_2>d.MoveNext() in /src/ES.Kubernetes.Reflector.CertManager/CertManagerMonitor.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at ES.Kubernetes.Reflector.Core.Monitoring.ManagedWatcher`3.Start() in /src/ES.Kubernetes.Reflector.Core/Monitoring/ManagedWatcher.cs:line 100
   at ES.Kubernetes.Reflector.CertManager.CertManagerMonitor.StartAsync(CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector.CertManager/CertManagerMonitor.cs:line 102
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at ES.Kubernetes.Reflector.Host.Program.Main(String[] args) in /src/ES.Kubernetes.Reflector.Host/Program.cs:line 33
```

I use the reflector to copy manually added tls-secrets by auto-mirroring.
Is this a config error or some bug?

The exakt same deployment works on another cluster which uses `Certificate` just perfect.

**Comment by winromulus** [comment]
@aeimer - Are you running cert-manager? If yes, what version?
Also are you running on a hosted kubernetes platform (AKS, GKE etc.)?

**Comment by aeimer** [comment]
So both envs are on Azure AKS. The one which works is with Cert-Manager 1.0.1. The non working has no cert-manager installed.

**Comment by winromulus** [comment]
@aeimer got it. I'll test this tomorrow with no cert-manager. Looks like a bug not covered when no cert-manager is installed.

**Comment by aeimer** [comment]
@winromulus Can I support you in the debugging process?

**Comment by winromulus** [comment]
@aeimer - Found the issue. Basically there are two parts. One is if cert-manager is not installed entirely, getting the CRD versions fault the service. The second is that even if the CRDs are installed, querying for certificates if there are none will not receive anything and will timeout. I have a bit more work to be done at the second part (working on this in the evenings).

**Comment by aeimer** [comment]
@winromulus - I see thank you for working :) Im not firm with dotnet so I can't help you. But if you need any sort of support tell me.

**Comment by winromulus** [comment]
@aeimer - Please try the latest version. It should now work even if cert-manager is not installed or uninstalled. Please reopen the issue if this is still a problem. You can also join our Slack channel (link in README) if you want to discuss this further or have additional problems with the new version.
Thanks for your patience on this.

**Comment by aeimer** [comment]
@winromulus Currently I deployed `helm.sh/chart: reflector-5.4.1` to a cluster _WITH_ cert-manager `1.0.1`. Seems to work, no errors so far. I'll update you if I have deployed it to the _NON_ cert-manager clusters.

**Comment by aeimer** [comment]
@winromulus I just installed it to a cluster _without_ cert-manager, the pod does not crash. I use version `5.4.7` in that env. Thank you for fixing the bug!

**Comment by sdandamudi5c** [comment]
@aeimer - Currently I am using v5.4.17 version of reflector but I am still facing this issue and we are not using cert-manager also. Can you please look at the below error suggest me a solution. 
```Error: 2021-02-09 01:16:42.453 +00:00 [ERR] (ES.Kubernetes.Reflector.CertManager.CertManagerMonitor) Exception occurred while processing `cert-manager` discovery
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'InternalServerError'
   at k8s.Kubernetes.ListCustomResourceDefinitionWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ListCustomResourceDefinitionAsync(IKubernetes operations, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.CertManager.CertManagerMonitor.OnCertManagerDiscovery() in /src/ES.Kubernetes.Reflector.CertManager/CertManagerMonitor.cs:line 207
   at ES.Kubernetes.Reflector.CertManager.CertManagerMonitor.<>c__DisplayClass11_0.<<StartAsync>g__ReadChannel|0>d.MoveNext() in /src/ES.Kubernetes.Reflector.CertManager/CertManagerMonitor.cs:line'''
